spring:
  datasource:
    url: jdbc:h2:mem:application_system_db
    username: jeh
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
          trace: false
          web-allow-others: false
  jpa:
    show-sql: true
    hibernate:
      properties:
        hibernate.format_sql: true
  flyway:
  
    
          
